### ISSUE TITLE
Question about Lambda.ResourceNotFoundException

### ISSUE THREAD

**Issue by nuskirk** [mavi888/stepfunction-triggers#2]
For the create step function, I do not use the same config as you: 
Of you: 
```yml
functions:
  calculateRandomNumber:
    handler: handler.calculateRandomNumber

stepFunctions:
  stateMachines:
    testingStateMachine:
      name: TestingStateMachine
      definition:
        Comment: "Example Step Function"
        StartAt: calculateRandomNumber
        States:
          calculateRandomNumber:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-calculateRandomNumber
            Next: moreCalculations
```

My config: 
```yml
functions:
  calculateRandomNumber:
    handler: handler.calculateRandomNumber
    name: demo

stepFunctions:
  stateMachines:
    testingStateMachine:
      name: TestingStateMachine
      definition:
        Comment: "Example Step Function"
        StartAt: calculateRandomNumber
        States:
          calculateRandomNumber:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-demo
            Next: moreCalculations
```

But I have an error after run step: 
```json
{
  "error": "Lambda.ResourceNotFoundException",
  "cause": "Function not found: <this is name function> (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 73402ff7-a57c-498f-bc12-asdasd323; Proxy: null)"
}
```
**Can help me if I config misstake**
